events {}

http {
    server {
        listen 443; # Plain HTTP on port 443 (No SSL certificates required for this test!)
        
        location / {
            # Route traffic to the API container on port 443
            proxy_pass http://medishare-api:443; 
        }
    }
}