name: Verify Code

# on: [push, pull_request]
on:
  push:
    branches:
      - main
  # pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        # run: npx eslint . --format sarif --output-file eslint-results.sarif
        run: npm run lint

      # THIS IS FOR INTEGRATING WITH GITHUB CODE SCANNING / SECURITY DASHBOARD
      # - name: Upload ESLint SARIF results
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: reports/eslint-results.sarif # Pointing to the generated SARIF file

      - name: Run unit testing
        run: npm test

  dependency-scan:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MyWebApp"
          path: "."
          format: "HTML"
          out: "scan-reports"
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Scan-reports
          path: scan-reports

